web/web/iot/urls.py
from django.urls import path
from iot import views


app_name = 'iot'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('', views.index, name='index'),
    path('json/random/', views.random_json, name='random_json'),
    path('files/imagen/', views.transferir_archivos, name='imagen1'),
    path('mostrar/sensores/', views.mostrar_sensores, name='sensores'),
    path('ajax/ejemplo/', views.ajax_ejemplo, name='ajax_ejemplo'),
    path('ajax/buttons/', views.ajax_buttons, name='ajax_buttons'),
    path('buttons/', views.web_botones),
]

web/web/proyecto/urls.py
from django.urls import path
from proyecto import views


app_name = 'proyecto'

urlpatterns = [
    path('',views.index,name = 'index'),
    path('json_response/',views.json_response, name = 'json_response'),
    path('general/',views.vista1,name='vista_general'),

]

web/web/sitio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('iot/', include('iot.urls')),
    path('proyecto/',include('proyecto.urls')),
    path('admin/', admin.site.urls),
]

web/web/iot/models.py
from django.db import models


class Sensor(models.Model):
    """
    La clase sensor de Python represtan una tabla de la base de datos
    Atributos de la clase representan los campos de la tabla
    """
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=30)
    tipo = models.CharField(max_length=30)  # Humedad, presion, ultrasonico

    def __str__(self):
        return f'Sensor: {self.name} tipo={self.tipo}'


class Measure(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    value = models.FloatField(default=0)
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)

    def __str__(self):
        return f'Medición: {self.value} | sensor={self.sensor.name}'


class MqttLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.message}'

web/web/proyecto/models.py
"""
Crea tabla dentro de base de datos
"""
from django.db import models

class EjemploMedicion(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    valor1 = models.FloatField(default=0)
    valor2 = models.FloatField(default=0)
    valor3 = models.FloatField(default=0)

    def __str__(self):
        return f'EjemploMedicion: {self.valor1},{self.valor2},{self.valor3}'

web/web/iot/views.py
import os
from random import randint

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, FileResponse
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.conf import settings
from iot.models import Sensor, Measure


def home(request):
    """el parametro request, es obligatorio y django inserta
    el parametro como un objet HTTP Request
    """
    variable = 10
    response = f'Bienvenido {variable}, esta es la respuesta más simpole en la interfaz web'
    return HttpResponse(response)


class AboutView(View):
    def get(self, request):
        nombre = request.GET.get('name')
        carnet = request.GET.get('carnet', 201500123)
        response = 'Esta es una pagina donde se desarrollan e implementa '
        response += 'tecnologias IoT '
        response += f'Parametro nombre = {nombre}, carnet = {carnet}'
        return HttpResponse(response)


def index(request):
    context = {
        'variable1': 10,
        'variable2': 20,
        'lista': [1, 2, 3, 4, 5]
    }
    return render(request, 'iot/index.html', context)


def random_json(request):
    data = {
        'descripcion': 'Se genera un valor random',
        'response': 'Tipo Json',
        'comentario': 'Json es parecido a python dicts',
        'numero': randint(1, 1000),
    }
    return JsonResponse(data)


def transferir_archivos(request):
    path = os.path.join(settings.BASE_DIR, 'iot/static/iot/imagen.jpeg')
    f = open(path, 'rb')
    return FileResponse(f, as_attachment=True, filename='imagen.jpeg')


def mostrar_sensores(request):
    Sensor.objects.create(name=f'Presion{randint(10,1000)}',
                          tipo='Presion')
    # sensores = Sensor.objects.all()
    sensores = Sensor.objects.all().order_by('-id')[:10]  # Solo los 10 ultimos
    context = {
        'sensores': sensores,
    }
    return render(request, 'iot/mostrar_sensores.html', context)


def ajax_ejemplo(request):
    """Simple llamada por ajax desde Javascript hacia el servidor"""
    data = {
        'message': f'Mensaje del servidor. Código es: {randint(1000, 1000000)}'
    }
    return JsonResponse(data)


#
# Ejemplo de comunicación Javascript Ajax con Django Python de forma asincrona
#

def web_botones(request):
    """
    Envia una plantilla html con el codigo para que un navegador la muestre
    """
    context = {}
    return render(request, 'iot/web_botones.html', context)


@csrf_exempt  # para desactivar la seguridad que Django solicita por POST
def ajax_buttons(request):
    """
    A traves de Javascript, se enviara por AJAX un GET o POST con información
    de los botones presionados.

    Se generar una muestra de medición aleatoria para enviarse de vuelta a
    Javascript y que la muestra en la página en tiempo real.
    """
    boton_id = request.POST.get('boton_id', None)
    print(f'Boton id {boton_id}')

    if boton_id == 'boton1':
        # Acciones ....
        pass
    elif boton_id == 'boton2':
        # Acciones ....
        pass
    else:
        # Acciones ....
        pass

    # Guardar una muestra aleatoria. Debe existir al menos un sensor guardado
    # en la base de datos
    try:
        sensor = Sensor.objects.filter().last()
    except Sensor.DoesNotExist:
        sensor = None

    Measure.objects.create(
        sensor=sensor, value=randint(0, 100)
    )

    # Obtener las ultimas n muestras
    muestras = Measure.objects.order_by('-created')[:10]
    ultimas_mediciones = list()
    for muestra in muestras:
        ultimas_mediciones.append(muestra.value)
    # print(ultimas_mediciones)

    data = {
        'mediciones': ultimas_mediciones,
    }
    return JsonResponse(data)

web/web/proyecto/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from proyecto.models import EjemploMedicion
import random 

# Create your views here.

def index(request):
    return JsonResponse({})

def vista1(request):
    context = {}
    return render(request, 'proyecto/pagina1.html',context)

@csrf_exempt
def json_response(request):
    #print(f'request.POST es: {request.POST}')
    carnet = request.POST.get('carnet',None)
    nombre = request.POST.get('nombre',None)
    print(carnet,nombre)

    # data = {
    #     'parametro1' : 'valor1',
    #     'parametro2' : 10,
    #     'parametro3' : None,
    # }

    valor_prueba = random.randint(10,50)
    
    EjemploMedicion.objects.create(valor1=valor_prueba)
    temporal = list()
    temporal1 = list()

    mediciones = EjemploMedicion.objects.order_by('-created')[:5]
    mediciones1 = EjemploMedicion.objects.order_by('-created')[:5]

    for medicion in mediciones:
        temporal.append(medicion.valor1)
    for medicion1 in mediciones1:
        temporal1.append(medicion1.valor1)

    
    data = {
        'mediciones' : temporal ,
        'mediciones1' : temporal1 ,
    }

    return JsonResponse(data)

web/web/data/templates/base/base.html
<!DOCTYPE HTML>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <h1>{% block principal %}{% endblock %}</h1>
    {% block content %}{% endblock %}

    <!-- Agregando JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block script %}{% endblock %}
</body>
</html>

web/web/iot/templates/iot/index.html
{% extends "base/base.html" %}


{% block style %}
<style>
    .encendido {
        background-color: #FBD603;
    }
    .apagado {
        background-color:gray;
    }
</style>
{% endblock %}


{% block title %}Inicio{% endblock %}


{% block principal %}Pagina principal para la App IoT{% endblock %}


{% block content %}
<p>Edge devices ...</p>
<p>Fog Netwkork: ...</p>
<h2>Variables enviadas como contexto</h2>
<p>variable1 {{ variable1 }}, variable2 {{ variable2 }}, lista {{ lista }}</p>

<div id="mostrar1" class="apagado">
    <p>hola</p>
</div>

<button class="btn" id="btn1">Encender</button>
<button class="btn" id="btn2">Apagar</button>
<button class="btn" id="btn3">Llamada asíncrona</button>

{% endblock %}


{% block script %}
<script>
    console.log("Log de consola JS");
    $(".btn").click(function (){
        console.log("boton presionado");
    });

    $("#btn1").click(function (){
        $("#mostrar1").removeClass("apagado");
        $("#mostrar1").addClass("encendido");
    });
    $("#btn2").click(function (){
        $("#mostrar1").removeClass("encendido").addClass("apagado");;
    });



    $("#btn3").click(function (){
        $.ajax({
            // type: "POST",
            type: "GET",
            dataType: "json",
            // headers: {"X-CSRFToken": "{{ csrf_token }}"},
            data: {'boton-id': 'btn3'},
            url: "{% url 'iot:ajax_ejemplo' %}"
        })
        .done(function(json_res, textStatus, jqXHR) {
            // console.log(json_res);
            console.log(`El servidor ha respondido: ${json_res.message}`);
        })
        .fail(function(json_res, textStatus, jqXHR) {
            console.log("No fue posible sincronizar con el servidor.");
        });
    });
</script>
{% endblock %}

web/web/iot/templates/iot/mostrar_sensores.html
{% extends "base/base.html" %}

{% block title %}Sensores{% endblock %}

{% block principal %}Mostrar sensores{% endblock %}

{% block content %}

<table>
    <thead>
        <th>Nombre</th>
        <th>Tipo</th>
    </thead>
    <tbody>
        {% for sensor in sensores %}
        <tr>
            <td>{{ sensor.name }}</td>
            <td>{{ sensor.tipo }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block script %}{% endblock %}

web/web/iot/templates/iot/web_botones.html
<!DOCTYPE HTML>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Ejemplo Ajax Botones</title>
</head>

<body>
    <h1>Presione botones</h1>

    <div id="buttons">
        <button id="boton1" class="btn">Boton1</button>
        <button id="boton2" class="btn">Boton2</button>
    </div>

    <br>

    <div id="mostrar"></div>



    <!-- Agregar jQuery para manipular facil ajax -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Aqui va todo el código de Javascript -->
    <script>

    // Ejecutar para cualquier boton presionado que tenga class=btn
    $(".btn").click(function (){
        boton_id = $(this).attr('id');  // obtener el id del boton que se presionó
        console.log(`Boton presionado: id=${boton_id}`)
        $.ajax({
            type: "POST",
            dataType: "json",
            // headers: {"X-CSRFToken": "{{ csrf_token }}"},
            data: {'boton_id': boton_id},
            url: "{% url 'iot:ajax_buttons' %}"  // Colocar aqui la url, esta se genera con Django
        })
        .done(function(json_res, textStatus, jqXHR) {
            // console.log(json_res);
            mediciones = json_res.mediciones;
            $("#mostrar").html("");
            console.log(`El servidor ha respondido: ${mediciones}`);
            for (i=0; i < mediciones.length; i++) {
                console.log(mediciones[i]);
                $("#mostrar").append(`${mediciones[i]} <br>`);
            }

        })
        .fail(function(json_res, textStatus, jqXHR) {
            console.log("No fue posible sincronizar con el servidor.");
            $("#mostrar").html(`Error no fue posible obtener datos`);
        });
    });
    </script>
</body>
</html>

web/web/proyecto/templates/proyecto/pagina.html
     <html>

            <head>
                <title>Control IoT - E3 </title>
                <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            </head>
            
            <body>
                <!-- Image and text -->
                <nav class="navbar navbar-default" style="background-color:#49EB8C!important;" role="navigation">
                    <a class="navbar-brand" href="#">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Black_Cat.svg/1200px-Black_Cat.svg.png" width="50" height="50" class="d-inline-block align-top" alt="">
                        <span class="text-dark">     Lab PIC'S   </span>
                    </a>
                </nav>
            
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-md-4">
                            <div class="card" style="width: 18rem;">
                                <img src="https://y4j9z9c2.stackpathcdn.com/media/catalog/product/cache/2/small_image/300x/9df78eab33525d08d6e5fb8d27136e95/1/0/102427557-1.jpg" class="card-img-top" width="500" height="300">
                                <div class="card-body">
                                    <h5 class="card-title">Sala</h5>
                                    <p class="card-text">Control de iluminacion</p>
                                    <a href="/?sala=on" class="btn btn-success">ON</a>
                                    <a href="/?sala=off" class="btn btn-danger">OFF</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-4">
                            <div class="card" style="width: 18rem;">
                                <img src="https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.elmueble.com%2Fmedio%2F2017%2F03%2F24%2Fcocina-abierta-al-comedor_079688cd.jpg&f=1&nofb=1" class="card-img-top" width="500" height="300">
                                <div class="card-body">
                                    <h5 class="card-title">Cocina</h5>
                                    <p class="card-text">Control de iluminacion.</p>
                                    <a href="/?cocina=on" class="btn btn-success">ON</a>
                                    <a href="/?cocina=off" class="btn btn-danger">OFF</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-4">
                            <div class="card" style="width: 18rem;">
                                <img src="https://www.ryterna.ee/wp-content/uploads/24-1300x867.jpg" class="card-img-top" width="500" height="300">
                                <div class="card-body">
                                    <h5 class="card-title">Puerta</h5>
                                    <p class="card-text">Abrir y cerrar.</p>
                                    <a href="/?garage=on" class="btn btn-success">ON</a>
                                    <a href="/?garage=off" class="btn btn-danger">OFF</a>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-4">
                            <div class="card" style="width: 18rem;">
                                <img src="https://bloximages.newyork1.vip.townnews.com/news-journal.com/content/tncms/assets/v3/editorial/a/5d/a5d08b90-21ba-11ea-860f-97d14da4e751/5dfa5ff308de6.image.jpg?resize=1200%2C1680" class="card-img-top" width="500" height="300">
                                <div class="card-body">
                                    <h5 class="card-title">Sanitario</h5>
                                    <p class="card-text">Control de iluminacion</p>
                                    <a href="/?sanitario=on" class="btn btn-success">ON</a>
                                    <a href="/?sanitario=off" class="btn btn-danger">OFF</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            
                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
            </body>
            
            </html>

web/web/proyecto/templates/proyecto/pagina1.html
<!DOCTYPE HTML>

<html>
<head>
    <title>Control IoT</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <!-- Image and text -->
        <nav class="navbar navbar-default" style="background-color:#83c9a0!important;" role="navigation">
            <a class="navbar-brand" href="#">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Black_Cat.svg/1200px-Black_Cat.svg.png" width="50" height="50" class="d-inline-block align-top" alt="">
                <span class="text-dark">    Control general de casa   </span>
            </a>
        </nav>
    <h1>Menú principal</h1>
    
    <div class="container">
        <div class="row">
            <div id="buttons">
                <button id="boton1" class="btn">Actualizar</button>
            </div>

            <br>
            <div id="mostrar"></div>
            
            <div id=tabla1>
                <!-- Agregar jQuery para manipular facil ajax -->
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
                <!-- Aqui va todo el código de Javascript -->
                <script>
                    // Ejecutar para cualquier boton presionado que tenga class=btn
                    $(".btn").click(function (){
                        boton_id = $(this).attr('id');  // obtener el id del boton que se presionó
                        console.log(`Boton presionado: id=${boton_id}`)
                        $.ajax({
                            type: "POST",
                            dataType: "json",
                            // headers: {"X-CSRFToken": "{{ csrf_token }}"},
                            data: {'boton_id': boton_id},
                            url: "{% url 'proyecto:json_response' %}"  // Colocar aqui la url, esta se genera con Django
                        })
                        .done(function(json_res, textStatus, jqXHR) {
                            console.log(json_res);
                            //$("#mostrar").html(`<p>${json_res.parametro1}</p><p>${json_res.parametro2}</p>`);
                            mediciones = json_res.mediciones;
                            $("#mostrar").html("");
                            console.log(`El servidor ha respondido: ${mediciones}`);
                            for (i=0; i < mediciones.length; i++) {
                                console.log(mediciones[i]);
                                $("#mostrar").append(`${mediciones[i]} <br>`);
                            }

                        })
                        .fail(function(json_res, textStatus, jqXHR) {
                            console.log("No fue posible sincronizar con el servidor.");
                            $("#mostrar").html(`Error no fue posible obtener datos`);
                        });
                });
                </script>
            </div>
        </div>
    </div>



</body>
</html>